# Generated by Django 4.2.20 on 2025-04-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_post_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="following",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="user",
        ),
        migrations.RemoveField(
            model_name="group",
            name="description",
        ),
        migrations.RemoveField(
            model_name="group",
            name="slug",
        ),
    ]
